version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: opec_redis
    ports:
      - '${REDIS_PORT:-6380}:6379'
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    restart: unless-stopped

volumes:
  redis_data:
